Repository SakshiPandey97/UniBazaar, pull requests merged in 2025-03, with the labels that each got.

#52 UI pallete change
  FE-UniBazaar/package-lock.json
  FE-UniBazaar/package.json
  FE-UniBazaar/src/.gitignore
  FE-UniBazaar/src/App.css
  FE-UniBazaar/src/App.jsx
  FE-UniBazaar/src/api/axios.js
  FE-UniBazaar/src/assets/imgs/banner.jpg
  FE-UniBazaar/src/assets/imgs/cloud_icon.svg
  FE-UniBazaar/src/assets/imgs/correct-upload.svg
  FE-UniBazaar/src/assets/imgs/file_icon.svg
  FE-UniBazaar/src/customComponents/InputField.jsx
  FE-UniBazaar/src/customComponents/Navbar.jsx
  FE-UniBazaar/src/customComponents/PasswordReqBox.jsx
  FE-UniBazaar/src/customComponents/ProductCard.jsx
  FE-UniBazaar/src/customComponents/Products.jsx
  FE-UniBazaar/src/customComponents/ShowProductPreview.jsx
  FE-UniBazaar/src/customComponents/UserLoginForm.jsx
  FE-UniBazaar/src/customComponents/UserRegisterForm.jsx
  FE-UniBazaar/src/hooks/useAnimation.jsx
  FE-UniBazaar/src/hooks/useAuthHandler.jsx
  FE-UniBazaar/src/hooks/useLoginModal.jsx
  FE-UniBazaar/src/hooks/useModal.jsx
  FE-UniBazaar/src/hooks/useNavBar.jsx
  FE-UniBazaar/src/hooks/useProductData.jsx
  FE-UniBazaar/src/pages/AuthPage.jsx
  FE-UniBazaar/src/pages/SellProductPage.jsx
  FE-UniBazaar/src/utils/generateStar.jsx
  FE-UniBazaar/src/utils/logger.js
  FE-UniBazaar/src/utils/prepareFormData.js
  FE-UniBazaar/src/utils/validSchema.js
Labels: frontend, sprint_w2

#54 Implemented messaging system backend
  Backend/messaging/db/database.go
  Backend/messaging/go.mod
  Backend/messaging/go.sum
  Backend/messaging/handler/message_handler.go
  Backend/messaging/handler/user_handler.go
  Backend/messaging/main.go
  Backend/messaging/models/message.go
  Backend/messaging/models/users.go
  Backend/messaging/repository/message_repository.go
  Backend/messaging/repository/user_repository.go
  Backend/messaging/websocket/websocket.go
Labels: backend

#64 Added unit tests
  FE-UniBazaar/package.json
  FE-UniBazaar/src/__tests__/api/api.test.jsx
  FE-UniBazaar/src/__tests__/customComponents/Banner.test.jsx
  FE-UniBazaar/src/__tests__/customComponents/InputField.test.jsx
  FE-UniBazaar/src/__tests__/customComponents/ProductCard.test.jsx
  FE-UniBazaar/src/__tests__/customComponents/Products.test.jsx
  FE-UniBazaar/src/__tests__/customComponents/Spinner.test.jsx
  FE-UniBazaar/src/__tests__/customComponents/UserLoginForm.test.jsx
  FE-UniBazaar/src/__tests__/customComponents/UserRegisterForm.test.jsx
  FE-UniBazaar/src/__tests__/hooks/useAnimation.test.jsx
  FE-UniBazaar/src/__tests__/hooks/useNavbar.test.jsx
  FE-UniBazaar/src/__tests__/hooks/useProductData.test.jsx
  FE-UniBazaar/src/__tests__/hooks/useProducts.test.jsx
  FE-UniBazaar/src/__tests__/hooks/useUserAuth.test.jsx
  FE-UniBazaar/src/__tests__/setupTests.js
  FE-UniBazaar/src/customComponents/Spinner.jsx
  FE-UniBazaar/vite.config.js
Labels: frontend, sprint_w2

#84 Jaws frontend
  Backend/messaging/go.mod
  Backend/messaging/go.sum
  Backend/messaging/handler/message_handler.go
  Backend/messaging/main.go
  Backend/messaging/models/conversation.go
  Backend/messaging/models/message.go
  Backend/messaging/msg_unit_test.go
  Backend/messaging/repository/message_repository.go
  Backend/messaging/websocket/websocket.go
  Backend/users/go.mod
  Backend/users/go.sum
  Backend/users/handler/routes.go
  Backend/users/server/server.go
  FE-UniBazaar/.gitignore
  FE-UniBazaar/package-lock.json
  FE-UniBazaar/src/App.jsx
  FE-UniBazaar/src/__tests__/customComponents/UserLoginForm.test.jsx
  FE-UniBazaar/src/api/axios.js
  FE-UniBazaar/src/customComponents/AnimatedRoutes.jsx
  FE-UniBazaar/src/customComponents/Navbar.jsx
  FE-UniBazaar/src/modal/product.js
  FE-UniBazaar/src/pages/Messaging.jsx
  FE-UniBazaar/src/utils/getUserId.js
  FE-UniBazaar/src/utils/prepareFormData.js
  package.json
Labels: frontend, sprint_w3

#85 Removed package-lock.json
  FE-UniBazaar/package-lock.json
  package.json
Labels: bug, sprint_w3

#87 Improved modularity of FE messaging.
  FE-UniBazaar/src/customComponents/MessageDisplay.jsx
  FE-UniBazaar/src/customComponents/WebsocketConnection.jsx
  FE-UniBazaar/src/hooks/useFetchMessages.jsx
  FE-UniBazaar/src/hooks/useFetchUsers.jsx
  FE-UniBazaar/src/hooks/useSendMessage.jsx
  FE-UniBazaar/src/hooks/useTypingIndicator.jsx
  FE-UniBazaar/src/pages/Messaging.jsx
Labels: enhancement, frontend, sprint_w3
